### ISSUE TITLE
ios8的Safari禁用了mata的minimal-ui，有好的解决方式吗？

### ISSUE THREAD

**Issue by xjchenhao** [iancj/qq#1]
我也在做单页面应用，跑在浏览器上的时候：浏览器的地址栏、工具栏和网页的header、tabnav混在一起，导致页面可视区域变小奇丑无比。怎么破啊... 
由于是模拟的滚动条，无法触发浏览器自带的滑动收起地址栏。

**Comment by iancj** [comment]
http://stackoverflow.com/questions/24889100/ios-8-removed-minimal-ui-viewport-property-are-there-other-soft-fullscreen
希望这篇文章能够帮到你

**Comment by xjchenhao** [comment]
这篇之前看过 还是解决不了，布局情况不一样。
